### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by rinigus** [nodevel/harbour-defender#10]
I would like to help to get Defender into Chum. It would require some small work on build scripts to make it possible to build at OBS, but I don't expect it to be anything major and would be happy to make the changes.

However, I noticed that Defender is missing a license. The only reference to any kind of license is to BSD at https://github.com/nodevel/harbour-defender/blob/master/src/harbour-defender.cpp#L6 . I presume it was just generated by SFOS SDK, so it cannot be really used as a reference of your intent.

Please either add a license or let me know your preference. I can add it to the set of commits together with build scripts changes. I was thinking to submit my changes to @peterleinchen fork as it looks to be a location where the current development is done. However, I presume you both would have to agree on license anyway. 

@peterleinchen, would you mind to open issues in your fork too?

**Comment by peterleinchen** [comment]
Hey rinigus,

I am not that active at the moment. So, sorry for the delay.
I would be glad if you could help getting defender into chum! :)

I will try to open issues at github...should be done!

I never heard anything from nodevel.
And I did not take a look at all regarding license(s).

Maybe GPL v3 (or any you like better BSD, MIT,...). I am open minded.

And yes, we should see github.com/peterleinchen/harbour-defender as the current repo.

All the best
PL



On Saturday, 8 January 2022, rinigus wrote:
> I would like to help to get Defender into Chum. It would require some small work on build scripts to make it possible to build at OBS, but I don't expect it to be anything major and would be happy to make the changes.
> 
> However, I noticed that Defender is missing a license. The only reference to any kind of license is to BSD at https://github.com/nodevel/harbour-defender/blob/master/src/harbour-defender.cpp#L6 . I presume it was just generated by SFOS SDK, so it cannot be really used as a reference of your intent.
> 
> Please either add a license or let me know your preference. I can add it to the set of commits together with build scripts changes. I was thinking to submit my changes to @peterleinchen fork as it looks to be a location where the current development is done. However, I presume you both would have to agree on license anyway. 
> 
> @peterleinchen, would you mind to open issues in your fork too?
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/nodevel/harbour-defender/issues/10
> You are receiving this because you were mentioned.
> 
> Message ID: ***@***.***

-- 
Peter Leinchen

Sent from my mobile device

**Comment by rinigus** [comment]
No problem with not being active, I'll be happy to contribute and get it to Chum. Assuming that you can set open source license. GPLv3 is fine by me, but I am just a user. So, if you think it is OK, let's go for it. 

I will close it over here and we can continue at your repo.
